apiVersion: batch/v1
kind: Job
metadata:
  name: dask-rhat2
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: dask-rhat2-driver
        image: quay.io/csams/rhat2
      restartPolicy: Never
